-- User Management: Google Auth + Roles + Invitations
-- Run in Supabase SQL Editor (Dashboard → SQL Editor)

-- 1. Enum for app roles
create type public.app_role as enum ('user', 'admin');

-- 2. User roles table (extends auth.users)
create table public.user_roles (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null unique,
  role public.app_role not null,
  created_at timestamptz default now()
);

comment on table public.user_roles is 'Application roles for each user.';

-- 3. Invitations table
create table public.invitations (
  id bigint generated by default as identity primary key,
  token uuid not null unique default gen_random_uuid(),
  created_by uuid references auth.users on delete set null,
  used_by uuid references auth.users on delete set null,
  used_at timestamptz,
  created_at timestamptz default now()
);

comment on table public.invitations is 'Invitation tokens for invitation-only sign up.';

-- 4. Custom Access Token Hook (injects user_role into JWT)
create or replace function public.custom_access_token_hook(event jsonb)
returns jsonb
language plpgsql
stable
as $$
  declare
    claims jsonb;
    user_role public.app_role;
  begin
    select role into user_role from public.user_roles where user_id = (event->>'user_id')::uuid;
    claims := event->'claims';

    if user_role is not null then
      claims := jsonb_set(claims, '{user_role}', to_jsonb(user_role));
    else
      claims := jsonb_set(claims, '{user_role}', 'null');
    end if;

    event := jsonb_set(event, '{claims}', claims);
    return event;
  end;
$$;

-- Grant auth admin access for the hook
grant usage on schema public to supabase_auth_admin;
grant execute on function public.custom_access_token_hook to supabase_auth_admin;
revoke execute on function public.custom_access_token_hook from authenticated, anon, public;
grant all on table public.user_roles to supabase_auth_admin;
revoke all on table public.user_roles from authenticated, anon, public;
create policy "Allow auth admin to read user roles" on public.user_roles
  as permissive for select to supabase_auth_admin using (true);

-- 5. RLS for user_roles (app access)
alter table public.user_roles enable row level security;

create policy "Users can read own role" on public.user_roles
  for select to authenticated
  using (auth.uid() = user_id);

create policy "Admins can read all roles" on public.user_roles
  for select to authenticated
  using ((auth.jwt() ->> 'user_role')::public.app_role = 'admin');

-- 6. RLS for invitations (app access)
alter table public.invitations enable row level security;

create policy "Admins can read invitations" on public.invitations
  for select to authenticated
  using ((auth.jwt() ->> 'user_role')::public.app_role = 'admin');

create policy "Admins can insert invitations" on public.invitations
  for insert to authenticated
  with check ((auth.jwt() ->> 'user_role')::public.app_role = 'admin');

-- Service role (backend) will bypass RLS for writes to user_roles and invitations

-- 7. View for listing users with email (service role reads auth.users)
create or replace view public.users_with_roles as
select ur.user_id as id, ur.role, u.email
from public.user_roles ur
join auth.users u on u.id = ur.user_id;
